### ISSUE TITLE
Status bar is not aligned with game board

### ISSUE THREAD

**Issue by edillingham** [edillingham/senet#1]
The bar with the status text is aligned way off to the left.  Probably a result of developing the game at a much lower screen resolution back in 2010.

This needs to be fixed to center on the page with the rest of the game board.

**Comment by adifinem** [comment]
the whole page uses funky positioning and probably needs redoing to be reactive and all that, but as committed "it works for me"

**Comment by edillingham** [comment]
Still broken after latest pull request.

![image](https://cloud.githubusercontent.com/assets/979051/14320383/b2441538-fbc9-11e5-9788-44ef2d0c032a.png)

**Comment by edillingham** [comment]
Works now, but only in Chrome. Opening new issue for Firefox.
